# Resolutions to train on, given as the side length of a square image. You can have multiple sizes here.
resolutions = [512]

# Enable aspect ratio bucketing and Frame buckets
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7
frame_buckets = [1, 33]


[[directory]]
# Path to directory of images/videos, and corresponding caption files. The caption files should match the media file name, but with a .txt extension.
# A missing caption file will log a warning, but then just train using an empty caption.
path = 'data/input/TRAINING_FOLDER'
num_repeats = 5
